export const GET_USERS = "GET_USERS";
export const ADD_DEMOGRAPHICS = "ADD_DEMOGRAPHICS";
export const ADD_IMMUNIZATION = "ADD_IMMUNIZATION";
export const ADD_MEDICATIONANDALLERGIES = "ADD_MEDICATIONANDALLERGIES";
export const UPDATE_PROFILEPIC = "UPDATE_PROFILEPIC";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";

export const PHYSICIANS = "PHYSICIANS";
export const PATIENTS = "PATIENTS";
export const NURSES = "NURSES";
export const GET_ALL_IMMUNIZATION = "GET_ALL_IMMUNIZATION";
export const ADD_USER = "ADD_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER = "GET_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_PATIENT_DEMOGRAPHICS = "GET_PATIENT_DEMOGRAPHICS";
export const GET_PATIENT_IMMUNIZATION = "GET_PATIENT_IMMUNIZATION";
export const SPECIALIZED_PHYSICIANS = "SPECIALIZED_PHYSICIANS";
export const PHYSICIAN_BY_NAME = "PHYSICIAN_BY_NAME";

export const GET_DEMOGRAPHICS = "GET_DEMOGRAPHICS";
export const GET_INACTIVE_USERS = "GET_INACTIVE_USERS";
export const UPDATE_INACTIVE_USERS = "UPDATE_INACTIVE_USERS";
export const GET_APPOINTMENT_DETAILS ="GET_APPOINTMENT_DETAILS";
