let appState = {
  users: [],
  demographics: [],
  immunization: [],
  vitals: [],
  medication_allergies: [],
  isLoggedIn: false,
  authToken: "",
  globalmessage: "",
  role: "",
  loggedUserInfo: {},
  physicians: [],
  patients: [],
  nurses: [],
  immunizations: [],
  userDetails: {},
  profileImage: "",
  inactiveUsers: [],
  patientDemographics: {},
  patientImmunization: {},
  specialisedPhysicians: [],
  inactiveUserCount: 0,
};

export default appState;
