let appState = {
  users: [],
  demographics: [],
  immunization: [],
  vitals: [],
  dietplan: [],
  medication_allergies: [],
  isLoggedIn: false,
  authToken: "",
  globalmessage: "",
  role: "",
  loggedUserInfo: {},
  physicians: [],
  patients: [],
  nurses: [],
  immunizations: [],
  userDetails: {},
  profileImage: "",
  inactiveUsers: [],
  approvedAppointments: [],
  patientDemographics: {},
  patientImmunization: {},
  specialisedPhysicians: [],
  appointmentsDetails: [],
  inactiveUserCount: 0,
  approvedAppointmentCount: 0,
  patientMedicationAllergy: [],
  labReports: [],
  pendingAppointmentCount: 0,
  pendingAppointments:[],
};

export default appState;
